


iotThingCertArn: arn:aws:iot:AWS_REGION:AWS_ACCOUNT_ID:cert/0123456789abcdefgh


iotThingClientIdArn: arn:aws:iot:AWS_REGION:AWS_ACCOUNT_ID:client/${iot:ClientId}


iotThingTopicArn: arn:aws:iot:AWS_REGION:AWS_ACCOUNT_ID:topic/12345abcd/aapghdiiot
